### ISSUE TITLE
Connect time out

### ISSUE THREAD

**Issue by ZNevzz** [ZNClub-Javascript/MY-ASA-WORLD#15]
com.mongodb.MongoSocketOpenException: Exception opening socket
        at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[mongo-java-driver-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.4.2.jar:na]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:113) ~[mongo-java-driver-3.4.2.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_131]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_131]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_131]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_131]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_131]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_131]
        at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:57) ~[mongo-java-driver-3.4.2.jar:na]
        at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongo-java-driver-3.4.2.jar:na]
        ... 3 common frames omitted

**Comment by ZNevzz** [comment]
No server chosen by ReadPreferenceServerSelector{readPreference=prim
ary} from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=myasaworld-shard-00-00-zadym.m
ongodb.net:27017, type=UNKNOWN, state=CONNECTING}, ServerDescription{address=myasaworld-shard-00-01-zadym.mongodb.net:27017, type=UNKNOWN, state=CONNECTING}, ServerDesc
ription{address=myasaworld-shard-00-02-zadym.mongodb.net:27017, type=UNKNOWN, state=CONNECTING}]}.

**Comment by ZNevzz** [comment]
Solutions / Strategies :
1. Deploy and check logs OR Wire it to controller responses 
2. Use Mongo Driver instead of Spring Data
3. Combinations of Spring Data with other modules 
4. File based database

**Comment by ZNevzz** [comment]
**Deploy and check logs**

**RESULTS**
1. App connected successfully
2. App logs saved
3. MongoDB Atlas View confirmed connections and read operations
4. Need Logger and Embedded H2 database for working in local app engine **docker** environment
